site_name: BIDS Extension Proposal Docs

theme: material

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md
  - Guide: guide.md
  - Submission Process: submission.md
  - The Schema: schema.md
